version: '3'
services:

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
      hostname: elasticsearch
      environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata01:/usr/share/elasticsearch/data
      ports:
        - 9300:9300
      networks:
        - d20

  kibana:
      image: docker.elastic.co/kibana/kibana:6.3.2
      ports:
        - "5601:5601"

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - d20

  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - d20

  gateway:
      hostname: gateway
      restart: always
      image: d20/gateway
      ports:
        - "8888:8888"
      networks:
        - d20

  config:
    hostname: config
    image: d20/config
    ports:
      - "5000:5000"
    networks:
      - d20

  discovery:
      hostname: discovery
      restart: always
      image: d20/discovery
      ports:
        - "8761:8761"
      networks:
        - d20

  mongo:
      hostname: mongo
      image: mongo
      ports:
        - "27017:27017"
      networks:
        - d20

  redis:
      hostname: redis
      image: redis:3.2-alpine
      ports:
        - "6379:6379"
      networks:
        - d20


networks:
  d20:
    driver: bridge